export default function TermsPage() {
  const updated = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const sections = [
    {
      number: "01",
      title: "Acceptance of Terms",
      content: [
        { label: "Agreement", text: "By accessing or using LEO, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform." },
        { label: "Updates", text: "We may revise these terms at any time. Continued use of LEO after changes constitutes your acceptance of the updated terms." },
      ],
    },
    {
      number: "02",
      title: "Use of the Platform",
      content: [
        { label: "Eligibility", text: "You must be at least 13 years old to use LEO. By using the platform, you confirm you meet this requirement." },
        { label: "Personal Use", text: "LEO is intended for personal, non-commercial use. You may not reproduce, resell, or exploit any part of the platform without written permission." },
        { label: "Responsible Use", text: "You agree not to misuse LEO, attempt to reverse-engineer any part of the service, or use it in any way that violates applicable laws." },
      ],
    },
    {
      number: "03",
      title: "AI-Generated Content",
      content: [
        { label: "Advisory Only", text: "All outfit suggestions, style analyses, and recommendations generated by LEO are for informational and entertainment purposes only." },
        { label: "No Guarantee", text: "LEO does not guarantee the accuracy, completeness, or suitability of any AI-generated content for your specific needs." },
        { label: "Your Responsibility", text: "Decisions made based on LEO's suggestions are solely your own. We are not liable for any outcomes resulting from acting on AI recommendations." },
      ],
    },
    {
      number: "04",
      title: "User Content",
      content: [
        { label: "Your Images", text: "You retain ownership of any images you upload. By uploading, you grant LEO a limited license to process them solely for analysis purposes." },
        { label: "Prohibited Content", text: "You may not upload content that is illegal, offensive, or violates the rights of others. We reserve the right to refuse or remove such content." },
      ],
    },
    {
      number: "05",
      title: "Account & Access",
      content: [
        { label: "Security", text: "You are responsible for maintaining the confidentiality of your account credentials. Notify us immediately of any unauthorized access." },
        { label: "Termination", text: "We reserve the right to suspend or terminate your account at our discretion if these terms are violated." },
      ],
    },
    {
      number: "06",
      title: "Limitation of Liability",
      content: [
        { label: "No Warranties", text: "LEO is provided 'as is' without warranties of any kind, express or implied." },
        { label: "Liability Cap", text: "To the maximum extent permitted by law, LEO shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform." },
      ],
    },
    {
      number: "07",
      title: "Intellectual Property",
      content: [
        { label: "Ownership", text: "All content, branding, design, and technology within LEO are the exclusive property of LEO and are protected by applicable intellectual property laws." },
        { label: "Restrictions", text: "You may not copy, modify, distribute, or create derivative works from any part of LEO without explicit written consent." },
      ],
    },
  ];

  return (
    <main className="min-h-screen bg-black text-white">

      {/* Hero */}
      <div className="relative border-b border-[#D4AF37]/20 px-6 py-24 text-center overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div style={{
            position: "absolute", top: "50%", left: "50%",
            transform: "translate(-50%, -50%)",
            width: "600px", height: "300px",
            background: "radial-gradient(ellipse, rgba(212,175,55,0.06) 0%, transparent 70%)",
          }} />
        </div>
        <p className="text-xs tracking-[0.4em] text-[#D4AF37]/60 uppercase mb-4">Legal</p>
        <h1 className="text-5xl font-bold text-white tracking-tight mb-4">
          Terms of <span className="text-[#D4AF37]">Service</span>
        </h1>
        <p className="text-neutral-500 text-sm">Last updated: {updated}</p>
        <p className="mt-6 text-neutral-400 text-sm max-w-lg mx-auto leading-relaxed">
          These terms govern your use of <span className="text-[#D4AF37] font-medium">LEO</span>.
          Please read them carefully before using the platform.
        </p>
      </div>

      {/* Sections */}
      <div className="mx-auto max-w-2xl px-6 py-16 space-y-0">
        {sections.map((section, si) => (
          <div key={si} className="border-b border-[#D4AF37]/10 py-10">
            <div className="flex items-start gap-6">
              <span className="text-[#D4AF37]/20 text-4xl font-bold leading-none mt-1 select-none shrink-0">
                {section.number}
              </span>
              <div className="flex-1 space-y-5">
                <h2 className="text-lg font-semibold text-white tracking-wide">
                  {section.title}
                </h2>
                <div className="space-y-4">
                  {section.content.map((item, ii) => (
                    <div key={ii} className="flex gap-3">
                      <div className="mt-1.5 w-1 h-1 rounded-full bg-[#D4AF37] shrink-0" />
                      <p className="text-sm text-neutral-400 leading-relaxed">
                        <span className="text-neutral-200 font-medium">{item.label} — </span>
                        {item.text}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="border-t border-[#D4AF37]/20 px-6 py-12 text-center space-y-4">
        <p className="text-[#D4AF37] font-bold tracking-[0.3em] text-lg">LEO</p>
        <p className="text-xs text-neutral-600">Crafted by AI. Worn by Kings.</p>
        <a
          href="/"
          className="inline-flex items-center gap-2 text-xs text-neutral-500 hover:text-[#D4AF37] transition-colors mt-2"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="19" y1="12" x2="5" y2="12" /><polyline points="12 19 5 12 12 5" />
          </svg>
          Back to LEO
        </a>
      </div>

    </main>
  );
}